### PR TITLE
Fixed the issue that methods return items before the clicked item becomes checked/unchecked

### PR DESCRIPTION
**Pull request by HectorWon**
Maybe this change can solve the problem that woemler reported in issue #22?

### CODE REVIEW

**Comment by Nelrohd** [comment]
Hi HectorWon,

Thank you for your PR. I just checked the code and the callback of the change event call the method this.onClickCheckbox which is now weird since it's not the same event. Could you rename onClickCheckbox into onChangeCheckbox?

In addition, I'm not sure to agree with the change of .gitignore in the same PR. I would prefer having different PR/commit.

Btw, did you run the tests as well?

Thank you very much,
Kevin

**Comment by HectorWon** [comment]
@Nelrohd 
Hi Kevin,

I just started front end programming 2 months ago, and I am not very familiar with git and github. I changed the pull request a little bit, hope this is what you want.

I don't know how to run the test file. I just opened the tests/index.html in the browser, and checked all three options. It reports 0 failed. But I am not sure whether it is the right way to run the tests.

Thanks,
Minxin

**Comment by Nelrohd** [comment]
Thanks @HectorWon and no problems.

About the tests, yes, it's just that. However it's not the best way to run test but I will improve it soon.

I would accept your PR if you fix your conflict with the current master so I can merge it. You can check the procedure there https://help.github.com/articles/fork-a-repo/#step-3-configure-git-to-sync-your-fork-with-the-original-spoon-knife-repository

Thank you again,
Kevin

**Comment by HectorWon** [comment]
Thanks for the link, Kevin. I think I've fixed the conflict. Maybe you can check if it is OK to merge now.

Thanks,
Minxin

**Comment by Nelrohd** [comment]
Thanks you very much, it's perfect.

Kevin

**Comment by Nelrohd** [comment]
Just a little thing: too avoid lot of commit (and mainly the ones reverted), you should squash them. http://stackoverflow.com/questions/8213926/git-simplest-way-of-squashing-commits-on-master

So after that, you will only see one big commit or the main commits at least.

**Comment by HectorWon** [comment]
Thanks for the link. I'll learn how to squash commits.

**Comment by Nelrohd** [comment]
@HectorWon No problem and thank you again for the PR. I will add soon the list of every single contributor in the README.md

**Comment by HectorWon** [comment]
@Nelrohd 
Hi Kevin,

I found the min.js file is not working. Maybe I didn't make it correct.

**Comment by Nelrohd** [comment]
Did you grunt it?

**Comment by HectorWon** [comment]
Yes, but maybe I forgot to grunt it again after the final change yesterday.

And I learned how to squash multiple commits. But it will not take effect on this one, since the PR is already merged, right?

**Comment by Nelrohd** [comment]
Everything is possible with GIT but it may be complicated and it's not always good to rewrite the history once is done. For the min.js, you will have to create a new PR.

**Pull request merged**
